var app, express, path;

express = require('express');
path = require('path');
app = express();

app.set('port', process.env.PORT || 3000);
app.set('views', path.join(__dirname, '/views'));
app.set('view engine', 'jade');
app.use(express.favicon(path.join(__dirname, '../public/favicon.ico')));
app.use(express.logger('dev'));
app.use(express.urlencoded());
app.use(express.json());
app.use(express.methodOverride());
app.use(express.cookieParser('frontend'));
app.use(app.router);
app.use(express["static"](path.join(__dirname, './public')));

app.locals.pretty = false;

if ('development' === app.get('env')) {
  app.use(express.errorHandler({
    dumpExceptions: true,
    showStack: true
  }));
  app.locals.pretty = true;
}

app.get('/', function(req, res) {
  return res.sendfile('./public/index.html');
});

app.listen(3000, function() {
  console.log('Template is running on port ' + 3000);
});

// ---
// generated by coffee-script 1.9.0
